create table "public"."ProjectFilters" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "project_id" bigint not null,
    "filter_id" bigint not null
);


alter table "public"."ProjectFilters" enable row level security;

CREATE UNIQUE INDEX "ProjectFilters_filter_id_key" ON public."ProjectFilters" USING btree (filter_id);

CREATE UNIQUE INDEX "ProjectFilters_pkey" ON public."ProjectFilters" USING btree (id);

CREATE UNIQUE INDEX "ProjectFilters_project_id_key" ON public."ProjectFilters" USING btree (project_id);

alter table "public"."ProjectFilters" add constraint "ProjectFilters_pkey" PRIMARY KEY using index "ProjectFilters_pkey";

alter table "public"."ProjectFilters" add constraint "ProjectFilters_filter_id_fkey" FOREIGN KEY (filter_id) REFERENCES "Filters"(id) not valid;

alter table "public"."ProjectFilters" validate constraint "ProjectFilters_filter_id_fkey";

alter table "public"."ProjectFilters" add constraint "ProjectFilters_filter_id_key" UNIQUE using index "ProjectFilters_filter_id_key";

alter table "public"."ProjectFilters" add constraint "ProjectFilters_project_id_fkey" FOREIGN KEY (project_id) REFERENCES "Projects"(id) not valid;

alter table "public"."ProjectFilters" validate constraint "ProjectFilters_project_id_fkey";

alter table "public"."ProjectFilters" add constraint "ProjectFilters_project_id_key" UNIQUE using index "ProjectFilters_project_id_key";

grant delete on table "public"."ProjectFilters" to "anon";

grant insert on table "public"."ProjectFilters" to "anon";

grant references on table "public"."ProjectFilters" to "anon";

grant select on table "public"."ProjectFilters" to "anon";

grant trigger on table "public"."ProjectFilters" to "anon";

grant truncate on table "public"."ProjectFilters" to "anon";

grant update on table "public"."ProjectFilters" to "anon";

grant delete on table "public"."ProjectFilters" to "authenticated";

grant insert on table "public"."ProjectFilters" to "authenticated";

grant references on table "public"."ProjectFilters" to "authenticated";

grant select on table "public"."ProjectFilters" to "authenticated";

grant trigger on table "public"."ProjectFilters" to "authenticated";

grant truncate on table "public"."ProjectFilters" to "authenticated";

grant update on table "public"."ProjectFilters" to "authenticated";

grant delete on table "public"."ProjectFilters" to "service_role";

grant insert on table "public"."ProjectFilters" to "service_role";

grant references on table "public"."ProjectFilters" to "service_role";

grant select on table "public"."ProjectFilters" to "service_role";

grant trigger on table "public"."ProjectFilters" to "service_role";

grant truncate on table "public"."ProjectFilters" to "service_role";

grant update on table "public"."ProjectFilters" to "service_role";

create policy "Enable read access for all users"
on "public"."ProjectFilters"
as permissive
for select
to public
using (true);



