create table "public"."Categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "problem_statement" text,
    "slug" text,
    "engineering_requirements" text,
    "order" text,
    "primary_image" text,
    "primary_image_alt" text,
    "resources" text,
    "token" character varying
);


alter table "public"."Categories" enable row level security;

CREATE UNIQUE INDEX "Categories_name_key" ON public."Categories" USING btree (name);

CREATE UNIQUE INDEX "Categories_pkey" ON public."Categories" USING btree (id);

CREATE UNIQUE INDEX "Categories_slug_key" ON public."Categories" USING btree (slug);

alter table "public"."Categories" add constraint "Categories_pkey" PRIMARY KEY using index "Categories_pkey";

alter table "public"."Categories" add constraint "Categories_name_key" UNIQUE using index "Categories_name_key";

alter table "public"."Categories" add constraint "Categories_slug_key" UNIQUE using index "Categories_slug_key";

grant delete on table "public"."Categories" to "anon";

grant insert on table "public"."Categories" to "anon";

grant references on table "public"."Categories" to "anon";

grant select on table "public"."Categories" to "anon";

grant trigger on table "public"."Categories" to "anon";

grant truncate on table "public"."Categories" to "anon";

grant update on table "public"."Categories" to "anon";

grant delete on table "public"."Categories" to "authenticated";

grant insert on table "public"."Categories" to "authenticated";

grant references on table "public"."Categories" to "authenticated";

grant select on table "public"."Categories" to "authenticated";

grant trigger on table "public"."Categories" to "authenticated";

grant truncate on table "public"."Categories" to "authenticated";

grant update on table "public"."Categories" to "authenticated";

grant delete on table "public"."Categories" to "service_role";

grant insert on table "public"."Categories" to "service_role";

grant references on table "public"."Categories" to "service_role";

grant select on table "public"."Categories" to "service_role";

grant trigger on table "public"."Categories" to "service_role";

grant truncate on table "public"."Categories" to "service_role";

grant update on table "public"."Categories" to "service_role";


